version: '3.7'

services:
  lovelab-batch:
    depends_on:
      - lovelab-batch-postgres
      - lovelab-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ["./wait-for-lovelab-api.sh","npm","start"]
  lovelab-api:
    image: basd4g/lovelab-api
    depends_on:
      - lovelab-batch-postgres
    env_file:
      - .env
    ports:
      - "0.0.0.0:80:3000"
    command: ["./wait-for-postgres.sh","npm","run","server"]
  lovelab-batch-postgres:
    image: postgres:11.6-alpine
    container_name: lovelab-batch-postgres
    expose:
      - "5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
      - batch-postgres-data-volume:/var/lib/postgresql/data/
    hostname: $POSTGRES_HOST
    user: $POSTGRES_USER
    env_file:
      - .env
    restart: always
volumes:
  batch-postgres-data-volume:
    name: lovelab-batch-postgres-data
    driver: local
