version: '3.7'

services:
  app:
    image: basd4g/lovelab-api
    depends_on:
      - lovelab-postgres
  lovelab-postgres:
    image: postgres:11.6-alpine
    container_name: lovelab-postgres-batch
    expose:
      - "5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
    hostname: $POSTGRES_HOST
    user: $POSTGRES_USER
